# Generated by Django 2.2.3 on 2019-07-22 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('favicon', models.ImageField(blank=True, upload_to='favicons/', verbose_name='Favicon')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('url', models.URLField(max_length=100, primary_key=True, serialize=False, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('add_by_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
